# Fly.io config for Nudge backend
# Replace 'Nudge-backend' with your Fly app name after `fly launch`
app = "Nudge-backend"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  # Comma-separated list of allowed origins for CORS
  # Example: https://Nudge.vercel.app,https://www.Nudge.app
  ALLOWED_ORIGINS = "http://localhost:3000,https://localhost"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

  [[http_service.checks]]
    grace_period = "5s"
    interval = "10s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    timeout = "2s"
